Added graphic image support on ZPL labels
OCA/report-print-send pull request #115
Opened 2017-11-02 09:25 UTC by JosDeGraeve

This PR adds support for graphic images on ZPL labels.

A new field type is defined which allow to print a static image or an image field.

TODO:
* update documentation

Depends on https://github.com/syleam/python-zpl2/pull/5

2017-11-02 09:26 UTC, JosDeGraeve commented
@legalsylvain Can you take a look on this PR ?

2017-11-04 16:58 UTC, JosDeGraeve commented
Travis is failing because wkhtmltopdf is not found.  Is this a known issue ??
https://travis-ci.org/OCA/report-print-send/jobs/297265169#L1374

2017-11-04 18:19 UTC, lasley commented
The 9.0 Travis doesn't have the Wkhtmltopdf declaration. Add:
* [This](https://github.com/OCA/report-print-send/blob/11.0/.travis.yml#L22-L24)
* [And this](https://github.com/OCA/report-print-send/blob/11.0/.travis.yml#L30)

2017-12-14 09:07 UTC, lmignon approved these changes
Thank you @JosDeGraeve This change works very well!

2017-12-14 17:06 UTC, lasley requested changes
Thanks @JosDeGraeve - looks good

Travis is timing out on wkhtmltopdf. You should be able to circumvent this by switching the test that interacts with it to `HttpCase`. I'd start by switching both just to make sure it works, then identify the correct one with a hunt and peck. Or just leave them both

2017-12-14 22:53 UTC, Garamotte requested changes
Thanks, some minor comments inline.

You didn't add any unit test, so I think rebasing on 9.0 and removing the changes you made in `.travis.yml` should fix Travis issues.

2017-12-14 22:53 UTC, sylvain-garancher commented on printer_zpl2/models/printing_label_zpl2_component.py
> +        "Image",
Please explicitely name all arguments.

2017-12-14 22:53 UTC, sylvain-garancher commented on printer_zpl2/views/printing_label_zpl2.xml
> +                            <page string="Format" attrs="{'invisible': [('component_type', 'in', ('sublabel'))]}">
The domain doesn't contain a tuple, but a string in brackets (there is no comma).

If you want to make it clearer, replace by `[('component_type', '=', 'sublabel')]`, but changing the operator from `=` to `in` adds a bug here :)

2017-12-14 22:53 UTC, sylvain-garancher commented on printer_zpl2/views/printing_label_zpl2.xml
> +                                    <field name="reverse_print" attrs="{'invisible': [('component_type', 'in', ('graphic'))]}"/>
`[('component_type', '=', 'graphic')]`

2017-12-14 22:53 UTC, sylvain-garancher commented on printer_zpl2/views/printing_label_zpl2.xml
> +                            <page string="Barcode Format" attrs="{'invisible': [('component_type', 'in', ('text', 'rectangle', 'circle', 'sublabel','graphic'))]}">
Please add a space after the comma.

2017-12-19 18:57 UTC, sylvain-garancher commented
@JosDeGraeve I created a branch on our fork based on yours: https://github.com/syleam/report-print-send/tree/9.0-printer_zpl2-add-graphics-support
The changes I proposed here are applied.

I also added the "reverse print" management for graphics, to print reversed color images and made some other minor changes.
Could you replace your branch by mine, if you agree with the changes ? Or maybe I can create a new PR to supersed this one ?

The PR on the zpl2 python module has been merged (with changes) and I released an 1.1 version on PyPI.

2021-12-19 12:01 UTC, closed without merging