[13.0][MIG] stock_picking_auto_print
OCA/report-print-send pull request #201
Opened 2020-02-13 06:43 UTC by Khalid-SerpentCS

Direct Print
=========
Auto print when DO is ready.

2020-03-23 18:20 UTC, dreispt commented
@Khalid-SerpentCS can you elapse fix the commit messages to match the original ones?

2020-03-23 18:25 UTC, dreispt requested changes
Some fixes needed

2020-03-23 18:25 UTC, dreispt commented on stock_picking_auto_print/__init__.py
> -# Copyright (C) 2019 Open Source Integrators
Don't remove the copyrights please

2020-03-23 18:25 UTC, dreispt commented on stock_picking_auto_print/models/stock_picking.py
> +                    if value.get("country_id")[0] == country_id:
You could have joined the nested if conditions, like you did above.

2020-03-23 18:25 UTC, dreispt commented on stock_picking_auto_print/models/stock_picking.py
> +                    if value.get("company_id")[0] == company_id:
same here

2020-03-26 06:51 UTC, bodedra commented
Ping @Khalid-SerpentCS

2020-03-27 08:15 UTC, bodedra commented
Ping @Chandresh-SerpentCS

2020-04-03 08:36 UTC, dreispt commented
Superseded by #209

2020-04-03 08:36 UTC, closed without merging