Add default label printer
OCA/report-print-send pull request #283
Opened 2022-06-08 06:51 UTC by ne1800

We have the case in the company that we have to print specific reports to a label printer. This should be done via the user printer. At the user it should be possible to set a label printer and a normal printer. At the report itself it should be defined if it is a label report.

This extension could perhaps help others.

2022-06-08 08:43 UTC, jbaudoux requested changes
It is better to add this in a new module `base_report_to_label_printer`
Just implement `_get_user_default_printer` in this module and extend it in the new module.

Can you also open a PR on https://github.com/OCA/wms/tree/14.0/shopfloor_workstation_label_printer
to depend on the new module and drop from `https://github.com/OCA/wms/blob/14.0/shopfloor_workstation_label_printer/models/res_users.py` what you moved here

2022-06-08 08:43 UTC, jbaudoux commented on base_report_to_printer/models/res_users.py
> +    default_label_printer_id = fields.Many2one(
That new field should also be added in `_register_hook` below.
We must allow the user to set a value in his preferences

2022-06-08 08:43 UTC, jbaudoux commented on base_report_to_printer/models/ir_actions_report.py
> +        if self.label:
move this in a function `_get_user_default_printer`

2022-06-08 08:45 UTC, jbaudoux commented
cc @simahawk @sebalix

2022-06-09 10:26 UTC, jbaudoux approved these changes
LGTM

Can you squash the commits?

2022-06-15 08:57 UTC, sebalix approved these changes
One small remark, LG

2022-06-15 08:57 UTC, sebalix commented on base_report_to_printer/models/ir_actions_report.py
> +        return user.printing_printer_id
```suggestion
        self.ensure_one()
        return user.printing_printer_id
```
As we will check `self.label` in the override.

2022-06-30 08:57 UTC, jbaudoux commented
cc @lmignon

2022-10-01 14:56 UTC, dreispt commented
/ocabot merge nobump

2022-12-09 07:16 UTC, TDu approved these changes

2022-12-16 12:23 UTC, simahawk commented
@ne1800 can you rebase pls?

2022-12-16 12:23 UTC, simahawk commented on base_report_to_printer/models/ir_actions_report.py
> +        return user.printing_printer_id
@ne1800 ping

2022-12-19 19:59 UTC, mt-software-de commented
> @ne1800 can you rebase pls?

@ne1800 is not available right now. 
I added his PR here https://github.com/jbaudoux/report-print-send/pull/2  maybe we can merge than both

2022-12-19 22:59 UTC, jbaudoux commented
Included in https://github.com/OCA/report-print-send/pull/310
This PR can be closed

2022-12-20 08:53 UTC, sebalix commented
@mt-software-de @jbaudoux we should not mix these two PRs to separate concerns, I'm using this one in one project but not the other.
If @ne1800 is not available I can re-open this one elsewhere so it can be merged ASAP.

2022-12-20 09:09 UTC, jbaudoux commented
> @mt-software-de @jbaudoux we should not mix these two PRs to separate concerns, I'm using this one in one project but not the other. If @ne1800 is not available I can re-open this one elsewhere so it can be merged ASAP.

Let's approve and merge the other PR, then you can use the module you want without relying on open PR
I need to include this PR in the other one for the glue module

2022-12-20 12:43 UTC, simahawk commented
> > @mt-software-de @jbaudoux we should not mix these two PRs to separate concerns, I'm using this one in one project but not the other. If @ne1800 is not available I can re-open this one elsewhere so it can be merged ASAP.
> 
> Let's approve and merge the other PR, then you can use the module you want without relying on open PR I need to include this PR in the other one for the glue module

@jbaudoux hmm sounds like the contrary.... we must merge the base PR 1st, which is this one.
We can take this over and finish it.

2022-12-20 12:47 UTC, simahawk commented
there you go https://github.com/OCA/report-print-send/pull/313

2022-12-20 12:47 UTC, closed without merging