Printer copies
OCA/report-print-send pull request #88
Opened 2017-05-22 08:59 UTC by jeanpaulrobineau

Hello,

This module will allow to specify per report or user/report the number of copies.
This is inspired by printer_tray module

kind regards,
Jean-Paul Robineau

2017-05-22 09:28 UTC, pedrobaeza commented
Please rename module to printer_copy_number, for not using plurals in module name as stated in OCA guidelines.

2017-05-22 09:39 UTC, jeanpaulrobineau commented
I renamed it

2017-05-22 09:42 UTC, pedrobaeza commented
Thanks!

2017-05-24 13:29 UTC, thomich commented
great feature.. lets merge it ;)

2017-06-02 13:13 UTC, Garamotte requested changes
Please add some unit tests and a `README.rst`.

Travis errors:
```
printer_copy_number/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
printer_copy_number/__manifest__.py:3: [C8103(manifest-deprecated-key), ] Deprecated key "description" in manifest file
```

2017-06-02 13:13 UTC, sylvain-garancher commented on printer_copy_number/models/res_users.py
> +    copies = fields.Integer(
I would prefer this field to be named `print_copy_count` or something like that, as the users model is very generic, `copies` could be anything.

2017-06-02 13:13 UTC, sylvain-garancher commented on printer_copy_number/views/ir_actions_report_xml.xml
> +  <data>
Replace `openerp` and `data` nodes by a single `odoo` node.

2017-06-02 13:13 UTC, sylvain-garancher commented on printer_copy_number/views/printing_report_xml_action.xml
> +  <data noupdate="0">
Replace `openerp` and `data` nodes by a single `odoo` node.
Specifying `noupdate="0"` is not needed (but not a problem).

2017-06-02 13:13 UTC, sylvain-garancher commented on printer_copy_number/views/res_users.xml
> +  <data>
Replace `openerp` and `data` nodes by a single `odoo` node.

2017-11-20 15:54 UTC, JosDeGraeve commented
@jeanpaulrobineau can you take another look at this PR ?

2021-11-28 12:01 UTC, closed without merging