Add a button to generate the ir.values for a model
OCA/report-print-send pull request #90
Opened 2017-06-08 19:40 UTC by JosDeGraeve

On the "ZPL II Labels" form, there are buttons added "Add in the 'More' menu" and
"Remove from the 'More' menu".

This way a user can easily set a print function for his label.

To add the buttons, i had to add a <sheet> tag on the form, indenting all form contents, hence the strange diff you see here on github.

2017-06-08 20:20 UTC, Garamotte requested changes
Thanks !
Don't worry about the diff being badly displayed by Github, we all know how to use git for that :)

I tested on runbot, it works, but the menu's name is always "Print Label", without the label name, which seems weird with several labels on the same model: we may want to add a menu item for each label, instead of duplicated items.
I think the best is to duplicate the action instead of simply linking it (and delete it when removing the menu item).This way, you can customize the new action's name (to include the label's name in the displayed menu item) and context (to select this label by default).

Also, a small unit test would be nice.

2017-06-08 20:20 UTC, Garamotte commented on printer_zpl2/models/printing_label_zpl2.py
> +                        _('Deletion of the action record failed.')
Could you add the name of the label when it fails ?
It will help in case we try to remove the menu from several labels at once.

2017-06-08 20:20 UTC, Garamotte commented on printer_zpl2/models/printing_label_zpl2.py
> +            if label.menu_ir_values_id:
Maybe merge the `for` and `if` statements using:
`for label in self.filtered('menu_ir_values_id'):`

2017-06-14 09:52 UTC, JosDeGraeve commented
Hello @sylvain-garancher,

As i did it now, there is an inconsistency indeed.

I propose these modifications:
* don't link the ir_values record to the label, because it is not specific for that label
* on the label form, move the 'add button', from the top of the sheet, next to the 'model' field.
* If the model already has a linked ir_values record, the button is replaced with a 'remove button'.

That would fix my use case to be more consistent.

What do you think ?

2017-06-20 17:36 UTC, sylvain-garancher commented
This is also an option.

I proposed to add label-specific action, you propose to add a label-generic action.
Both are valid, and I have no preference about that, so do it the way you prefer :)
Or maybe someone else has an opinion ?

2021-11-28 12:01 UTC, closed without merging